#!/bin/bash

# This script rebuilds the algorithmically-generated ftml files.

set -e

if [ ! -f wscript ]
then
	echo "Must be in the root of the project"
	exit 2
fi

# configure tests
tests="AllChars Proof Diac Matras Conjuncts Nuktas"
urls='url(../references/Badami-Regular.ttf)=refR url(../results/Badami-Regular.ttf)=R url(../references/NotoSerifKannada-Regular.ttf)=NotoSerif url(../references/NotoSansKannada-Regular.ttf)=NotoSans url(../references/NotoSansKannadaUI-Regular.ttf)=NotoSansUI url(../references/TiroKannada-Regular.ttf)=Tiro url(../references/BalooTamma2-Regular.ttf)=Baloo'
ufo='source/Badami-Regular.ufo'

# list all the fonts to test
fonts=''
for url in $urls
do
	fonts="$fonts -s '$url'"
done

echo "Rebuilding ftml files..."
for test in $tests
do
	base=${test,,}
	title="\"${test} auto\""
	ftml=tests/${base}.ftml
	log=tests/logs/${base}.log
	eval tools/psfgenftml.py -q -t "$title" --scale 200 -i source/glyph_data-Badami.csv --xsl ../tools/ftml.xsl "$fonts" -l $log $ufo $ftml &
done
wait
echo "done."
