#!/bin/bash

# This script rebuilds the algorithmically-generated ftml files.

set -e

if [ ! -f wscript ]
then
	echo "Must be in the root of the project"
	exit 2
fi

# configure tests
tests="AllChars Proof Diac Matras Conjuncts Nuktas"
urls='url(../references/Badami-Regular.ttf)=refR url(../references/Badami-Bold.ttf)=refB url(../references/Badami-Italic.ttf)=refI url(../references/Badami-BoldItalic.ttf)=refBI url(../results/Badami-Regular.ttf)=R url(../results/Badami-Bold.ttf)=B url(../results/Badami-Italic.ttf)=I url(../results/Badami-BoldItalic.ttf)=BI url(../references/NotoSerifKannada-Regular.ttf)=notoSerif url(../references/NotoSansKannada-Regular.ttf)=notoSans url(../references/NotoSansKannadaUI-Regular.ttf)=notoSansUI url(../references/TiroKannada-Regular.ttf)=tiro url(../references/BalooTamma2-Regular.ttf)=baloo url(../results/Kaveri-Regular.ttf)=kR url(../results/Kaveri-Bold.ttf)=kB url(../results/Kaveri-Italic.ttf)=kI url(../results/Kaveri-BoldItalic.ttf)=kBI'
ufo='source/Badami-Regular.ufo'

# list all the fonts to test
fonts=''
for url in $urls
do
	fonts="$fonts -s '$url'"
done

echo "Rebuilding ftml files..."
for test in $tests
do
	base=${test,,}
	title="\"${test} auto\""
	ftml=tests/${base}.ftml
	log=tests/logs/${base}.log
	eval tools/psfgenftml.py -q -t "$title" --prevfont references/Badami-Regular.ttf --norendercheck --scale 200 -i source/glyph_data-Badami.csv --xsl ../tools/ftml.xsl "$fonts" -l $log $ufo $ftml &
done
wait
echo "done."
