#!/bin/sh

for ufo in source/*.ufo
do
    psfnormalize -v 3 -p checkfix=fix $ufo &
done
wait

faces="Badami Kaveri"
for face in $faces
do
    ufo=source/${face}-Regular.ufo
    psfsetkeys -k "copyright" --filepart OFL.txt $ufo
    psfsetkeys -k "openTypeNameLicense" --file OFL.txt $ufo
    psfsetversion $ufo 0.301
    psfsetglyphorder -i source/glyph_data-${face}.csv $ufo
    psfsetpsnames -i source/glyph_data-${face}.csv $ufo
    psfmakewoffmetadata -n ${face} -i in.nlci.fonts $ufo # --populateufowoff --force
    psfsyncmasters source/${face}Roman.designspace source/${face}Italic.designspace
done
