#!/bin/bash

faces=(Badami Kaveri)
styles=(Regular Bold Italic "Bold Italic")
desc_long="Kannada script font for all languages using the Kannada script"

export nlci=$HOME/script/tools
export src=source
source ${nlci}/prepare.bash

pushd ${src}
fontforge -script ${nlci}/emsize1000.ff Kaveri-Regular.sfd
popd

source ${nlci}/metadata.bash

pushd manual_aps
for ufo in *.ufo
do
    basefont=$(basename $ufo .ufo)
    psfexportanchors $ufo ${basefont}_ap.xml
    psfaddanchors -i ${basefont}_ap.xml ../${src}/$ufo
    ../tools/anchors.py ../${src}/$ufo
done
popd

rm -f ${src}/*-???*.sfd*
./preflight
echo "done producing UFO sources"
