#!/usr/bin/python3

Vowels = [
    0x0C85,  # KANNADA LETTER A
    0x0C86,  # KANNADA LETTER AA
    0x0C87,  # KANNADA LETTER I
    0x0C88,  # KANNADA LETTER II
    0x0C89,  # KANNADA LETTER U
    0x0C8A,  # KANNADA LETTER UU
    0x0C8B,  # KANNADA LETTER VOCALIC R
    0x0C8C,  # KANNADA LETTER VOCALIC L
    0x0C8E,  # KANNADA LETTER E
    0x0C8F,  # KANNADA LETTER EE
    0x0C90,  # KANNADA LETTER AI
    0x0C92,  # KANNADA LETTER O
    0x0C93,  # KANNADA LETTER OO
    0x0C94,  # KANNADA LETTER AU
    ]

Matras = [
    0x0CBE,  # KANNADA VOWEL SIGN AA
    0x0CBF,  # KANNADA VOWEL SIGN I
    0x0CC0,  # KANNADA VOWEL SIGN II
    0x0CC1,  # KANNADA VOWEL SIGN U
    0x0CC2,  # KANNADA VOWEL SIGN UU
    0x0CC3,  # KANNADA VOWEL SIGN VOCALIC R
    0x0CC4,  # KANNADA VOWEL SIGN VOCALIC RR
    0x0CC6,  # KANNADA VOWEL SIGN E
    0x0CC7,  # KANNADA VOWEL SIGN EE
    0x0CC8,  # KANNADA VOWEL SIGN AI
    0x0CCA,  # KANNADA VOWEL SIGN O
    0x0CCB,  # KANNADA VOWEL SIGN OO
    0x0CCC,  # KANNADA VOWEL SIGN AU
    ]

Consonants = [
    0x0C95,  # KANNADA LETTER KA
    0x0C96,  # KANNADA LETTER KHA
    0x0C97,  # KANNADA LETTER GA
    0x0C98,  # KANNADA LETTER GHA
    0x0C99,  # KANNADA LETTER NGA
    0x0C9A,  # KANNADA LETTER CA
    0x0C9B,  # KANNADA LETTER CHA
    0x0C9C,  # KANNADA LETTER JA
    0x0C9D,  # KANNADA LETTER JHA
    0x0C9E,  # KANNADA LETTER NYA
    0x0C9F,  # KANNADA LETTER TTA
    0x0CA0,  # KANNADA LETTER TTHA
    0x0CA1,  # KANNADA LETTER DDA
    0x0CA2,  # KANNADA LETTER DDHA
    0x0CA3,  # KANNADA LETTER NNA
    0x0CA4,  # KANNADA LETTER TA
    0x0CA5,  # KANNADA LETTER THA
    0x0CA6,  # KANNADA LETTER DA
    0x0CA7,  # KANNADA LETTER DHA
    0x0CA8,  # KANNADA LETTER NA
    0x0CAA,  # KANNADA LETTER PA
    0x0CAB,  # KANNADA LETTER PHA
    0x0CAC,  # KANNADA LETTER BA
    0x0CAD,  # KANNADA LETTER BHA
    0x0CAE,  # KANNADA LETTER MA
    0x0CAF,  # KANNADA LETTER YA
    0x0CB0,  # KANNADA LETTER RA
    0x0CB1,  # KANNADA LETTER RRA
    0x0CB2,  # KANNADA LETTER LA
    0x0CB3,  # KANNADA LETTER LLA
    0x0CDE,  # KANNADA LETTER FA
    0x0CB5,  # KANNADA LETTER VA
    0x0CB6,  # KANNADA LETTER SHA
    0x0CB7,  # KANNADA LETTER SSA
    0x0CB8,  # KANNADA LETTER SA
    0x0CB9,  # KANNADA LETTER HA
    ]

Nukta = [
    0x0CBC,  # KANNADA SIGN NUKTA
    ]

Virama = [
    0x0CCD,  # KANNADA SIGN VIRAMA
    ]

vowels = list(map(chr, Vowels))
matras = list(map(chr, Matras))
consonants = list(map(chr, Consonants))
n = nukta = list(map(chr, Nukta))[0]
h = virama = list(map(chr, Virama))[0]

ka = consonants[0]
ga = consonants[2]
gha = consonants[3]
ja = consonants[7]
nya = consonants[9]
ssa = consonants[33]

Akhands = [
    ka + h + ssa,  # KaSsa
    ja + h + nya,  # JaNya
    ]

akhands = Akhands
